[tox]
isolated_build = True
envlist = stubtest,mypy-plugins

[testenv:stubtest]
runner = uv-venv-runner
deps =
    django>=5.2,<5.3
    mypy>=1.19.1
    Pillow>=9.1.0
setenv =
    DJANGO_SETTINGS_MODULE=tests.django_settings
commands =
    python -m mypy.stubtest willow --allowlist stubtest-allowlist.txt

[testenv:mypy-plugins]
runner = uv-venv-runner
deps =
    django>=5.2,<5.3
    django-stubs>=5.2.9
    pytest>=8.0
    pytest-mypy-plugins>=3.0
    mypy>=1.19.1
commands =
    pytest tests/ --mypy-same-process {posargs}
