from typing import IO, Any

from willow.image import (
    AvifImageFile,
    GIFImageFile,
    IcoImageFile,
    Image,
    ImageFile,
    JPEGImageFile,
    PNGImageFile,
    RGBAImageBuffer,
    RGBImageBuffer,
    WebPImageFile,
)

class UnsupportedRotation(Exception): ...

class WandImage(Image):
    image: Any
    def __init__(self, image: Any) -> None: ...
    @classmethod
    def check(cls) -> None: ...
    @classmethod
    def is_format_supported(cls, image_format: str) -> bool: ...
    def get_size(self) -> tuple[int, int]: ...
    def get_frame_count(self) -> int: ...
    def has_alpha(self) -> bool: ...
    def has_animation(self) -> bool: ...
    def resize(self, size: tuple[int, int]) -> WandImage: ...
    def crop(self, rect: tuple[int, int, int, int]) -> WandImage: ...
    def rotate(self, angle: int) -> WandImage: ...
    def set_background_color_rgb(
        self, color: tuple[int, int, int] | list[int]
    ) -> WandImage: ...
    def get_icc_profile(self) -> bytes | None: ...
    def get_exif_data(self) -> bytes | None: ...
    def save_as_jpeg(
        self,
        f: IO[bytes],
        quality: int = 85,
        progressive: bool = False,
        apply_optimizers: bool = True,
        **kwargs: Any,
    ) -> JPEGImageFile: ...
    def save_as_png(
        self,
        f: IO[bytes],
        apply_optimizers: bool = True,
        **kwargs: Any,
    ) -> PNGImageFile: ...
    def save_as_gif(
        self, f: IO[bytes], apply_optimizers: bool = True
    ) -> GIFImageFile: ...
    def save_as_webp(
        self,
        f: IO[bytes],
        quality: int = 80,
        lossless: bool = False,
        apply_optimizers: bool = True,
    ) -> WebPImageFile: ...
    def save_as_avif(
        self,
        f: IO[bytes],
        quality: int = 80,
        lossless: bool = False,
        apply_optimizers: bool = True,
    ) -> AvifImageFile: ...
    def save_as_ico(
        self, f: IO[bytes], apply_optimizers: bool = True
    ) -> IcoImageFile: ...
    def auto_orient(self) -> WandImage: ...
    def get_wand_image(self) -> Any: ...
    @classmethod
    def open(cls, image_file: IO[bytes] | ImageFile) -> WandImage: ...
    def to_buffer_rgb(self) -> RGBImageBuffer: ...
    def to_buffer_rgba(self) -> RGBAImageBuffer: ...

willow_image_classes: list[type[WandImage]]
